title: Robert Schofield
description: #
baseurl: "/" # the subpath of your site, e.g. /blog
url: "robertaidenschofield.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: light # Or use dark

# Profile information
name: Robert Schofield
tagline: Developer
about-description: Full time Computer Science student at Florida International University. Fluent in Java, C, HTML/CSS, PHP, SQL, and Python. # Add Discription
pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: robertschofieldphotography@gmail.com # Add your Email address
phone: 954 608 4909 # Add your Phone number

github: robertaidenschofield # Add your Github handle


# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
